# Generated by Django 3.2.7 on 2021-09-26 08:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0002_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='TempEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=255)),
                ('domain', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mail.user')),
            ],
        ),
        migrations.DeleteModel(
            name='SendMailLogs',
        ),
        migrations.DeleteModel(
            name='TempMail',
        ),
    ]
