# Generated by Django 3.2.7 on 2021-09-26 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0003_auto_20210926_1126'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tempemail',
            old_name='user_id',
            new_name='user',
        ),
    ]
